### ISSUE TITLE
PC Speaker settings in Options menu does not seem to save (PC Speaker False after restart)

### ISSUE THREAD

**Issue by Gagert** [libretro/dosbox-svn#12] opened 2019-10-21 21:47 UTC
In the configs I have for the PC Speaker Enabled games, I have to open the text-file itself and set dosbox_svn_pcspeaker = "true" because it seems like the core Options menu does not save this setting for certain games. The core itself sets pcspeaker = "false" after restarting RetroArch with the game, so I have to make those *.opt files Read Only to keep PC Speaker enabled.

The Option menu saves settings like the Emulated Machine option, so there might be a bug here?

Edit: This seems to also be an issue when it comes to editing the irq and hdma settings in some of my game  configs as well. Some of my configs (*.opt) accepts the changes I even make to the PC Speaker Settings, while some of the game configs don't. It seems a bit inconsistent at the time.

**Comment by realnc** [comment] 2019-10-29 02:27
Are you starting the core directly, or are you loading a `.conf` file in RA?

**Comment by Gagert** [comment] 2019-10-30 23:56
Those particular games that I'm having this pcspeaker = false issue with, are games that I load directly through it's exe file (through RetroArch with this core) and not through its *.conf file.

In the games I do load with the *.conf file (for enabling iso file through d: or enabling Gravis Ultrasound), I haven't entered any settings that's related to either PC Speaker or Soundblaster in the *.conf file itself.

It's just a plain text-file with only the absolute required text inside to mount the game and start its *.exe file, Gravis Ultrasound and such.

I have created game-options files for almost all of the games I run through this libretro core (I like to isolate all my config files to not conflict with each other).

**Comment by realnc** [comment] 2019-10-31 01:21
I meant the RA core options config files, not the dosbox .conf files. In RA, you can save core options on a per-game basis, and it's very easy to do so by accident. You only have to activate the first entry in the core options menu that says "Create game options file". Once you do, all your settings when loading that particular game are going to be reset to those stored in that game-specific options file.

So check your retroarch configuration folder and see if there's `.opt` files for those games. They should be in the `config/DOSBox-SVN/` folder.

**Comment by Gagert** [comment] 2019-10-31 01:59
I have saved *.opt files for every game I'm running in this libretro core in a per-game basis. I have opened my folder inside RA\config\DOSBox-SVN and opened the *.opt files for the selected files inside Notepad to see the settings.

The same files has to be made read-only for those games which uses the PC Speaker settings, because somehow RA decides to undo the changes I recently made if I activated PC Speakers in this core (once I restart RA and the selected game the previous settings gets overwritten if the *.opt files are not made read-only).

As noted in my first post in this topic, some settings can be changed on a per-game basis, and keep the saved changes after restarting RA and the game. Settings like PC Speaker and ira + hdma settings lives its own life on my Windows 10 PC, meaning that separate *.opt config files for the selected games doesn't always keep the changes I made previous after restarting RA.

The Emulate Machine option gets saved on a per-game basis without issues, while the PC Speaker setting is harder for me to make lasting changes to (after enabling it) after restarting RA.

**Comment by DukeSkinny** [comment] 2019-10-31 09:53
Chiming in just to note that I'm having this same problem with IRQ & DMA settings. Does not matter whether I change the settings within RA (per-game core options file enabled), or if I directly edit the *.opt - when I restart the core, all settings are returned to their previous value.

These game are loaded through *.conf files, though I make sure to match whatever values between the files. *.opt file values will change automatically, *.conf file values stay static (how I defined them).

**Comment by realnc** [comment] 2019-11-08 14:05
I cannot reproduce any of this :-/

**Comment by Gagert** [comment] 2019-11-08 20:56
Maybe this already has been fix with a newer build of this libretro core? I'll have to ckeck this later on by creating new configs from scratch with the newest build of this core.

**Comment by Gagert** [comment] 2019-11-08 23:33
I removed the Read Only label for all the *.opt files in this core, while also having upgraded from RetroArch 1.7.9 to 1.8.1.

Seems like there's no issues now, like it previously was.

Should I close this issue from this issue tracker then? There was another user in this thread who also had issues with the IRQ & DMA settings as I had. Maybe we hear from him again?

**Comment by realnc** [comment] 2019-11-10 11:00
@DukeSkinny Is this still happening for you with RA 1.8.1 and latest dosbox-svn core?

**Comment by DukeSkinny** [comment] 2019-11-11 12:29
All working as intended over here. Feel free to close this.

**Closed** 2019-11-11 16:22 UTC
